# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "foreman_epel_release"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mikael Fridh"]
  s.date = "2013-01-03"
  s.description = "Redirect to the latest available epel-release package for your OS release"
  s.email = "mfridh@marinsoftware.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/foreman_epel_release/epel_controller.rb",
    "config/routes.rb",
    "foreman_epel_release.gemspec",
    "init.rb",
    "install.rb",
    "lib/foreman_epel_release.rb",
    "lib/foreman_epel_release/engine.rb",
    "test/foreman_epel_release_test.rb",
    "test/helper.rb",
    "test/test_foreman-epel_release.rb",
    "test/test_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/frimik/foreman_epel_release"
  s.licenses = ["GPL-3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Foreman engine plugin for epel-release package fetching"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

